name: Build and Push to Docker Hub
on:
  push:
    branches:
      - develop
      - main

env:
  IMAGE_NAME: bytebook-config-server
  DOCKERHUB_REPO: roman3455/bytebook-config-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short commit hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Extract version from RELEASE_VERSION.txt
        id: get_version
        run: |
          line=$(head -n 1 RELEASE_VERSION.txt)
          VERSION=${line%% *}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image on main branch
        if: github.ref == 'refs/heads/main'
        run: |
          docker build \
            --build-arg VERSION=${{ env.VERSION }} \
            --build-arg GIT_COMMIT=${{ env.COMMIT_HASH }} \
            -t $DOCKERHUB_REPO:${{ env.VERSION }} \
            .
          docker tag $DOCKERHUB_REPO:${{ env.VERSION }} $DOCKERHUB_REPO:latest
          docker push $DOCKERHUB_REPO:${{ env.VERSION }}
          docker push $DOCKERHUB_REPO:latest

      - name: Build and push Docker image on develop branch
        if: github.ref == 'refs/heads/develop'
        run: |
          docker build \
            --build-arg VERSION=${{ env.VERSION }} \
            --build-arg GIT_COMMIT=${{ env.COMMIT_HASH }} \
            -t $DOCKERHUB_REPO:${{ env.VERSION }}-${{ env.COMMIT_HASH }} \
            .
          docker push $DOCKERHUB_REPO:${{ env.VERSION }}-${{ env.COMMIT_HASH }}
